package com.example.car_eloung;

public class DataConstants {

    final static String price[] = {"12050-50000",
            "50000-67900",
            "67900-84900",
            "84900-99900",
            "99900-134900",
            "135000-166900",
            "166900-220000",
            "220000-340000",
            "340000-600000",
            "600000-9500000"};



    //final static String topseed[] = {"120-170","171-250","251-420"};
    //final static String power[] = {"65-300","301-700","701-1500"};
    //final static String torque[] = {"90-350","351-600","601-1600"};

    final static String body[] = {"3-door",
            "5-door",
            "2-door",
            "4-door"};

    final static String style[] = {
            "hatchback",
            "wagon",
            "coupe",
            "sedan",
            "convertible",
            "liftback",
            "long sedan",
            "pickup",
            "minivan",
            "van",
            "long wagon",
            "midsize",
            "long pickup"
    };

    final static String label[] = {
            "Abarth 595 Competizione",
            "Abarth 695",
            "Acura MDX",
            "Acura NSX",
            "Acura RDX",
            "Acura TLX",
            "Alfa Romeo Giulia",
            "Alfa Romeo Giulia Quadrifoglio",
            "Alfa Romeo Giulietta",
            "Alfa Romeo Stelvio",
            "Alfa Romeo Stelvio Quadrifoglio",
            "Aston Martin DB11",
            "Aston Martin DB11 Volante",
            "Aston Martin DBS",
            "Aston Martin DBX",
            "Aston Martin Rapide",
            "Aston Martin V8 Vantage",
            "Aston Martin Vanquish",
            "Aston Martin Vanquish Volante",
            "Audi A3 Sedan",
            "Audi A4",
            "Audi A5 Cabriolet",
            "Audi A5",
            "Audi A5 Sportback",
            "Audi A6",
            "Audi A7",
            "Audi A8",
            "Audi E-Tron",
            "Audi E-Tron Sportback",
            "Audi Q3",
            "Audi Q3 Sportback",
            "Audi Q5",
            "Audi Q7",
            "Audi Q8",
            "Audi R8",
            "Audi R8 Spyder",
            "Audi RS 3",
            "Audi RS 5",
            "Audi RS 5 Sportback",
            "Audi RS 6",
            "Audi RS 7",
            "Audi RS Q3",
            "Audi RS Q8",
            "Audi S Q5",
            "Audi S3",
            "Audi S4",
            "Audi S5",
            "Audi S6",
            "Audi S8",
            "BAIC A1",
            "BAIC A5 Sedan",
            "BAIC BJ40 Plus",
            "BAIC D20",
            "Bentley Bentayga",
            "Bentley Continental GT",
            "Bentley Continental GTC",
            "Bentley Flying Spur",
            "Bentley Mulsanne",
            "BMW 2-Series",
            "BMW 2-Series Gran",
            "BMW 3-Series",
            "BMW 4-Series",
            "BMW 4-Series Gran",
            "BMW 5-Series",
            "BMW 6-Series Gran Turismo",
            "BMW 7-Series",
            "BMW 8-Series",
            "BMW 8-Series Gran",
            "BMW I8",
            "BMW M2",
            "BMW M3",
            "BMW M4",
            "BMW M5",
            "BMW M8",
            "BMW X1",
            "BMW X2",
            "BMW X3",
            "BMW X4",
            "BMW X5",
            "BMW X5 M",
            "BMW X6",
            "BMW X6 M",
            "BMW X7",
            "BMW Z4",
            "Borgward BX5",
            "Borgward BX7",
            "Brilliance FRV",
            "Brilliance FRV Cross",
            "Brilliance FSV",
            "Brilliance H530",
            "Brilliance V5",
            "Bugatti Chiron",
            "BYD F3",
            "BYD S6",
            "Cadillac CT4",
            "Cadillac CT4-V",
            "Cadillac CT5",
            "Cadillac CT5-V",
            "Cadillac Escalade",
            "Cadillac XT4",
            "Cadillac XT5",
            "Cadillac XT6",
            "Caterham Seven",
            "Changan Alsvin",
            "Changan CS35",
            "Changan CS35 Plus",
            "Changan CS75",
            "Changan CS85",
            "Changan CS95",
            "Changan Eado",
            "Chery Arrizo 3",
            "Chery Arrizo 5",
            "Chery Arrizo 7",
            "Chery Tiggo 3",
            "Chery Tiggo 5",
            "Chery Tiggo 7",
            "Chevrolet Aveo",
            "Chevrolet Blazer",
            "Chevrolet Bolt",
            "Chevrolet Camaro",
            "Chevrolet Captiva",
            "Chevrolet Corvette",
            "Chevrolet Equinox",
            "Chevrolet Malibu",
            "Chevrolet Silverado",
            "Chevrolet Spark",
            "Chevrolet Suburban",
            "Chevrolet Tahoe",
            "Chevrolet Traverse",
            "Chevrolet Trax",
            "Chrysler 300 SRT",
            "Chrysler 300C",
            "Chrysler Pacifica",
            "Citroen C-Elysee",
            "Citroen C3",
            "Citroen C4",
            "Citroen C5",
            "Citroen DS3",
            "Citroen DS4",
            "Citroen DS5",
            "CMC Z7",
            "Daihatsu Gran Max Pickup",
            "Daihatsu Gran Max Van",
            "Daihatsu Terios",
            "Dodge Challenger",
            "Dodge Challenger SRT",
            "Dodge Charger",
            "Dodge Charger SRT",
            "Dodge Durango",
            "Dodge Durango SRT",
            "Dongfeng H30 Cross",
            "Dongfeng S30",
            "Dorcen G60S",
            "Dorcen G70S",
            "FAW Besturn X40",
            "FAW Besturn X80",
            "Ferrari 812 Superfast",
            "Ferrari F8 Tributo",
            "Ferrari Portofino",
            "Ferrari Roma",
            "Ferrari SF90 Stradale",
            "Fiat 500",
            "Fiat 500X",
            "Fiat Ducato",
            "Fiat Fiorino",
            "Ford Bronco",
            "Ford Bronco 2-Door",
            "Ford Bronco Sport",
            "Ford Ecosport",
            "Ford Edge",
            "Ford Escape",
            "Ford Escort",
            "Ford Expedition",
            "Ford Explorer",
            "Ford F-150",
            "Ford F-150 Raptor",
            "Ford Figo",
            "Ford Mustang",
            "Ford Ranger",
            "Ford Shelby GT500",
            "Ford Taurus",
            "Ford Tourneo Custom",
            "Ford Transit",
            "Ford Transit Custom",
            "Foton SUP",
            "Foton SUP 2014",
            "Foton Tunland",
            "Foton View C1 Minibus",
            "GAC GA3",
            "GAC GA5",
            "GAC GA8",
            "GAC GN8",
            "GAC GS3",
            "GAC GS4",
            "GAC GS5",
            "GAC GS7",
            "GAC GS8",
            "Geely Emgrand 7",
            "Geely Emgrand 8",
            "Geely Emgrand GS",
            "Geely Emgrand GT",
            "Geely Emgrand X7",
            "Geely Emgrand X7 Sport",
            "Geely GC2",
            "Geely GC6",
            "Geely GC7",
            "Geely GX2",
            "Genesis G70",
            "Genesis G80",
            "Genesis G90",
            "Genesis GV80",
            "GMC Acadia",
            "GMC Sierra 1500",
            "GMC Terrain",
            "GMC Yukon",
            "Great Wall Wingle 5",
            "Great Wall Wingle 6",
            "Great Wall Wingle 7",
            "Haval H2 Crossover",
            "Haval H6",
            "Haval H9",
            "Honda Accord",
            "Honda City",
            "Honda Civic",
            "Honda CR-V",
            "Honda HR-V",
            "Honda Odyssey",
            "Honda Odyssey J",
            "Honda Pilot",
            "Hongqi H5",
            "Hongqi H7",
            "Hongqi H9",
            "Hongqi HS5",
            "Hongqi HS7",
            "Hyundai Accent",
            "Hyundai Accent 2014",
            "Hyundai Accent 2013",
            "Hyundai Accent 2012",
            "Hyundai Accent 2011",
            "Hyundai Accent 2010",
            "Hyundai Accent 2009",
            "Hyundai Accent 2008",
            "Hyundai Accent 2007",
            "Hyundai Accent 2006",
            "Hyundai Azera",
            "Hyundai Creta",
            "Hyundai Elantra",
            "Hyundai Grand I10",
            "Hyundai Grand Santa Fe",
            "Hyundai Grand Santa Fe 2014",
            "Hyundai H1",
            "Hyundai Kona",
            "Hyundai Palisade",
            "Hyundai Santa Fe",
            "Hyundai Sonata",
            "Hyundai Tucson",
            "Hyundai Veloster N",
            "Hyundai Veloster Turbo",
            "Infiniti Q30",
            "Infiniti Q50",
            "Infiniti Q60",
            "Infiniti Q70",
            "Infiniti QX30",
            "Infiniti QX50",
            "Infiniti QX60",
            "Infiniti QX70",
            "Infiniti QX80",
            "Isuzu D-Max",
            "Isuzu MU-X",
            "JAC M5 MPV",
            "JAC S3 SUV",
            "JAC S7",
            "Jaguar E-Pace",
            "Jaguar F-Pace",
            "Jaguar F-Type",
            "Jaguar F-Type SVR",
            "Jaguar I-Pace",
            "Jaguar XE",
            "Jaguar XF",
            "Jaguar XF Sportbrake",
            "Jaguar XFR-S",
            "Jaguar XJ",
            "Jeep Cherokee",
            "Jeep Compass",
            "Jeep Gladiator",
            "Jeep Grand Cherokee",
            "Jeep Grand Cherokee SRT",
            "Jeep Grand Cherokee Trackhawk",
            "Jeep Renegade",
            "Jeep Wrangler",
            "Jeep Wrangler Unlimited",
            "Kia Cadenza",
            "Kia Carens",
            "Kia Carnival",
            "Kia Cerato",
            "Kia K5",
            "Kia K900",
            "Kia Mohave",
            "Kia Niro",
            "Kia Optima",
            "Kia Pegas",
            "Kia Picanto",
            "Kia Rio",
            "Kia Rio Hatchback",
            "Kia Seltos",
            "Kia Sorento",
            "Kia Soul",
            "Kia Sportage",
            "Kia Stinger",
            "Kia Telluride",
            "King Long Mini Van",
            "KTM X-Bow",
            "Lamborghini Aventador",
            "Lamborghini Aventador Roadster",
            "Lamborghini Huracan",
            "Lamborghini Huracan Spyder",
            "Lamborghini Urus",
            "Land Rover Defender",
            "Land Rover Discovery",
            "Land Rover Discovery Sport",
            "Land Rover Range Rover",
            "Land Rover Range Rover Evoque",
            "Land Rover Range Rover Sport",
            "Land Rover Range Rover Sport SVR",
            "Land Rover Range Rover Velar",
            "Lexus ES",
            "Lexus GS",
            "Lexus GX",
            "Lexus IS",
            "Lexus LC",
            "Lexus LS",
            "Lexus LX",
            "Lexus NX",
            "Lexus RC",
            "Lexus RC F",
            "Lexus RX",
            "Lexus UX",
            "Lincoln Aviator",
            "Lincoln Continental",
            "Lincoln Corsair",
            "Lincoln MKC",
            "Lincoln MKZ",
            "Lincoln Nautilus",
            "Lincoln Navigator",
            "Lincoln Navigator L",
            "Lotus Elise",
            "Lotus Evora",
            "Lotus Exige",
            "Luxgen S5",
            "Luxgen U6",
            "Mahindra Scorpio Pikup",
            "Mahindra XUV500",
            "Maserati Ghibli",
            "Maserati Levante",
            "Maserati Quattroporte",
            "Maxus D90",
            "Maxus G10",
            "Maxus T60 Pickup",
            "Maxus V80",
            "Mazda 2",
            "Mazda 3",
            "Mazda 3 Sedan",
            "Mazda 6",
            "Mazda CX-3",
            "Mazda CX-30",
            "Mazda CX-5",
            "Mazda CX-9",
            "Mazda MX-5",
            "Mazda MX-5 RF",
            "McLaren 540C",
            "McLaren 570GT",
            "McLaren 570S",
            "McLaren 570S Spider",
            "McLaren 650S",
            "McLaren 650S Spider",
            "McLaren 720S",
            "McLaren 765LT",
            "McLaren GT",
            "Mercedes-Benz A 35 AMG",
            "Mercedes-Benz A 45 AMG",
            "Mercedes-Benz A-Class",
            "Mercedes-Benz A-Class Sedan",
            "Mercedes-Benz AMG GT",
            "Mercedes-Benz AMG GT 4-Door",
            "Mercedes-Benz AMG GT Roadster",
            "Mercedes-Benz C 63 AMG",
            "Mercedes-Benz C-Class",
            "Mercedes-Benz CLA 35 AMG",
            "Mercedes-Benz CLA 45 AMG",
            "Mercedes-Benz CLA-Class",
            "Mercedes-Benz CLS 53 AMG",
            "Mercedes-Benz CLS-Class",
            "Mercedes-Benz E 53 AMG",
            "Mercedes-Benz E 63 AMG",
            "Mercedes-Benz E-Class",
            "Mercedes-Benz EQC",
            "Mercedes-Benz G 63 AMG",
            "Mercedes-Benz G-Class",
            "Mercedes-Benz GLA-Class",
            "Mercedes-Benz GLB",
            "Mercedes-Benz GLC 43 AMG",
            "Mercedes-Benz GLC 63 AMG",
            "Mercedes-Benz GLC-Class",
            "Mercedes-Benz GLE 63 AMG",
            "Mercedes-Benz GLE-Class",
            "Mercedes-Benz GLS 63 AMG",
            "Mercedes-Benz GLS-Class",
            "Mercedes-Benz S 63 AMG",
            "Mercedes-Benz S 65 AMG",
            "Mercedes-Benz S-Class",
            "Mercedes-Benz S-Class Maybach",
            "Mercedes-Benz Sprinter",
            "Mercedes-Benz V-Class",
            "Mercedes-Benz Vito",
            "MG 5",
            "MG 6",
            "MG HS",
            "MG RX5",
            "MG RX8",
            "MG ZS",
            "Mini Clubman",
            "Mini Cooper",
            "Mini Cooper 5-Door",
            "Mini Countryman",
            "Mitsubishi ASX",
            "Mitsubishi Attrage",
            "Mitsubishi Eclipse Cross",
            "Mitsubishi L200",
            "Mitsubishi Montero Sport",
            "Mitsubishi Outlander",
            "Mitsubishi Outlander PHEV",
            "Mitsubishi Pajero",
            "Mitsubishi Pajero SWB",
            "Morgan 3 Wheeler",
            "Morgan Aero8",
            "Morgan Plus 4",
            "Morgan Plus 8",
            "Morgan Roadster",
            "Nissan Altima",
            "Nissan GT-R",
            "Nissan Kicks",
            "Nissan Leaf",
            "Nissan Maxima",
            "Nissan Micra",
            "Nissan Navara",
            "Nissan Pathfinder",
            "Nissan Patrol",
            "Nissan Patrol Pickup",
            "Nissan Patrol Safari",
            "Nissan Sentra",
            "Nissan Sunny",
            "Nissan Urvan",
            "Nissan X-Trail",
            "Nissan Xterra",
            "Noble M600",
            "Opel Astra",
            "Opel Crossland X",
            "Opel Grandland X",
            "Opel Insignia",
            "Opel Zafira Life",
            "Pagani Huayra",
            "Peugeot 2008",
            "Peugeot 208",
            "Peugeot 3008",
            "Peugeot 308",
            "Peugeot 5008",
            "Peugeot 508",
            "Peugeot Boxer",
            "Peugeot Expert",
            "Peugeot Partner",
            "PGO Cevennes",
            "PGO Speedster",
            "Porsche 911",
            "Porsche 911 Cabriolet",
            "Porsche 911 GT2",
            "Porsche 911 GT3",
            "Porsche 911 Targa",
            "Porsche 911 Turbo",
            "Porsche 911 Turbo Cabriolet",
            "Porsche 918 Spyder",
            "Porsche Boxster",
            "Porsche Cayenne",
            "Porsche Cayman",
            "Porsche Macan",
            "Porsche Panamera",
            "Porsche Taycan",
            "Porsche Taycan Turbo",
            "Ram 1200",
            "Ram 1500",
            "Ram 1500 TRX",
            "Ram 2500",
            "Renault Dokker Van",
            "Renault Duster",
            "Renault Koleos",
            "Renault Megane",
            "Renault Megane RS",
            "Renault Symbol",
            "Renault Zoe",
            "Rolls Royce Cullinan",
            "Rolls Royce Dawn",
            "Rolls Royce Ghost",
            "Rolls Royce Phantom",
            "Rolls Royce Wraith",
            "Seat Ibiza",
            "Skoda Fabia",
            "Skoda Kodiaq",
            "Skoda Octavia",
            "Skoda Superb",
            "Soueast DX3",
            "Soueast DX7",
            "Ssangyong Actyon",
            "Ssangyong Korando",
            "Ssangyong Rexton",
            "Ssangyong Tivoli",
            "Subaru BRZ",
            "Subaru Forester",
            "Subaru Impreza",
            "Subaru Impreza WRX",
            "Subaru Impreza WRX STI",
            "Subaru Legacy",
            "Subaru Outback",
            "Subaru XV",
            "Suzuki Baleno",
            "Suzuki Carry",
            "Suzuki Ciaz",
            "Suzuki Ertiga",
            "Suzuki Grand Vitara",
            "Suzuki Ignis Crossover",
            "Suzuki Jimny",
            "Suzuki Swift",
            "Suzuki Swift Dzire",
            "Suzuki Vitara",
            "Tata Xenon",
            "Tesla Cybertruck",
            "Tesla Model 3",
            "Tesla Model S",
            "Tesla Model X",
            "Tesla Model Y",
            "Toyota Avalon",
            "Toyota Avanza",
            "Toyota C-HR",
            "Toyota Camry",
            "Toyota Corolla",
            "Toyota FJ Cruiser",
            "Toyota Fortuner",
            "Toyota Granvia",
            "Toyota Hiace",
            "Toyota Highlander",
            "Toyota Hilux",
            "Toyota Innova",
            "Toyota Land Cruiser",
            "Toyota Land Cruiser 70",
            "Toyota Land Cruiser Pickup",
            "Toyota Land Cruiser Prado",
            "Toyota Land Cruiser Prado SWB",
            "Toyota Previa",
            "Toyota RAV-4",
            "Toyota Rush",
            "Toyota Supra",
            "Toyota Yaris Sedan",
            "Volkswagen Amarok",
            "Volkswagen Golf",
            "Volkswagen Golf GTI",
            "Volkswagen Golf R",
            "Volkswagen Multivan",
            "Volkswagen Passat",
            "Volkswagen T-Roc",
            "Volkswagen Teramont",
            "Volkswagen Tiguan",
            "Volkswagen Touareg",
            "Volvo S60",
            "Volvo S90",
            "Volvo V40",
            "Volvo V60",
            "Volvo V60 Polestar",
            "Volvo V70",
            "Volvo V90",
            "Volvo XC40",
            "Volvo XC60",
            "Volvo XC70",
            "Volvo XC90",
            "ZNA Rich"
    };

    final static String country[] =
            {
                    "Italy",
                    "United States",
                    "United Kingdom",
                    "Germany",
                    "Belgium",
                    "Spain",
                    "Slovakia",
                    "China",
                    "Austria",
                    "South Korea",
                    "Mexico",
                    "Canada",
                    "France",
                    "Taiwan",
                    "Indonesia",
                    "Japan",
                    "Serbia",
                    "Turkey",
                    "India",
                    "South Africa",
                    "Thailand",
                    "Czech Republic",
                    "Hungary",
                    "Russia",
                    "Morocco",
                    "Romania",
                    "Argentina",
                    "Portugal",
                    "Sweden"
            };

}
